live_config_reload = true

[colors]
cursor = { text = "CellBackground", cursor = "CellForeground" }

[colors.normal]
black = "0x282c34"
blue = "0x51afef"
cyan = "0x46d9ff"
green = "0x98be65"
magenta = "0xc678dd"
red = "0xff6c6b"
white = "0xbbc2cf"
yellow = "0xecbe7b"

[colors.primary]
background = "0x282c34"
foreground = "0xbbc2cf"

[font]
size = 13

[font.bold]
family = "Hack Nerd Font" # MesloLGL Nerd Font Mono
style = "bold"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "None"
position = "None"
dynamic_padding = true


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 10
